spring.application.name=chatbot
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=Enrique
spring.datasource.password=Enrique123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
