spring.application.name=chatbot
# Config DB
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=Enrique
spring.datasource.password=Enrique123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Forzar ejecución de data.sql en arranque
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
